#!/usr/bin/env bash

if [ -e "paper.tex" ]
then
    exit 1
fi

DIALOG="$(which dialog)"

if [ -z "$DIALOG" ]
then
    echo "Error: command 'dialog' not found, please install http://invisible-island.net/dialog/dialog.html. Maybe via 'apt-get install dialog'"
    exit 1
fi

while [ "$TYPE" != "a4" -a "$TYPE" != "a5" -a "$TYPE" != "presentation" ]
do
    TYPE=$("$DIALOG" --radiolist "Choose the type (mark selection with spacebar)" 100 100 50 a4 A4 a4 a5 A5 a5 presentation Presentation presentation 3>&1 1>&2 2>&3)
done

mv "paper-$TYPE.tex" "paper.tex"
rm paper-*

if [ "$TYPE" != "presentation" ]
then
    rm ktu_back_bright.png ktu_back_dark.png ktu_front.png
fi

if [ "$TYPE" != "a4" ]
then
    rm mya4.sty
fi

if [ "$TYPE" != "a5" ]
then
    rm mya5.sty
fi

while ! [ -d "$REFDIR" ]
do
    REFDIR=$(dialog --inputbox "Enter path to existing directory with BibTeX (.bib) files" 100 100 3>&1 1>&2 2>&3)
done

echo "$REFDIR" > ./refdir
if ! [ "$REFDIR" = "." ]
then
    mv *.bib references.bib
    touch references.bib
fi

rm README.md initialize kramdown-mylatex.rb
