#!/usr/bin/env bash

if [ -z "$1" ]
then
    echo "Error: file with references list not specified." >&2
    exit 1
fi

REFLIST="$(realpath "$1")"

if ! [ -f "$REFLIST" ]
then
    echo "Error: file with references list \"$REFLIST\" does not exist." >&2
    exit 1
fi

if [ -z "$2" ]
then
    echo "Error: directory with references not specified." >&2
    exit 1
fi

REFDIR="$(realpath "$2")"

if ! [ -d "$REFDIR" ]
then
    echo "Error: directory with references \"$REFDIR\" does not exist." >&2
    exit 1
fi

REFDIR="$(realpath "$2")"

cat "$REFLIST" | grep -v '^#' | while read REF
do
    cat "$REFDIR/${REF}.bib"
    echo
done
